Repository lbryio/lbry-sdk, pull requests merged in 2019-05, with the labels that each got.

#2076 make ttfb configurable, fix race condition on writers, ban on time scales, remove idle code for getting unstuck on long downloads, fix foreign key error and improve downloader loop checks
  lbrynet/blob/blob_file.py
  lbrynet/blob_exchange/client.py
  lbrynet/blob_exchange/downloader.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/stream_manager.py
  scripts/time_to_first_byte.py
  tests/integration/test_file_commands.py
  tests/unit/blob/test_blob_file.py
Labels: area: downloads, type: improvement

#2080 fixed bug where lbrynet failed to start with single-key accounts in the wallet
  lbrynet/wallet/account.py
  tests/unit/wallet/test_account.py
Labels: area: wallet, type: bug

#2081 `account_list` defaults to 0 confirmations for balance
  lbrynet/extras/daemon/Daemon.py
Labels: area: api, type: improvement

#2083 make save_file a parameter instead of a flag so it obeys conf
  lbrynet/extras/daemon/Daemon.py
Labels: type: fixup

#2082 fix incorrect media-type of .cbr archives
  lbrynet/schema/mime_types.py
Labels: area: blobs/files, type: bug

#2092 Set should_announce=1 to head and descriptor blobs when saving a stream to database
  lbrynet/extras/daemon/Components.py
  lbrynet/extras/daemon/migrator/migrate9to10.py
  lbrynet/extras/daemon/storage.py
  tests/integration/test_file_commands.py
  tests/unit/stream/test_managed_stream.py
  tests/unit/stream/test_reflector.py
Labels: area: database, type: bug

#2093 Refactor announcer + fixups for last db migrator code
  lbrynet/dht/blob_announcer.py
  lbrynet/extras/daemon/migrator/dbmigrator.py
  lbrynet/extras/daemon/migrator/migrate9to10.py
  tests/unit/dht/test_blob_announcer.py
Labels: area: DHT, area: reflector

#2095 add saved_file and content_fee columns to file table
  lbrynet/blob_exchange/client.py
  lbrynet/extras/daemon/Components.py
  lbrynet/extras/daemon/migrator/dbmigrator.py
  lbrynet/extras/daemon/migrator/migrate10to11.py
  lbrynet/extras/daemon/storage.py
  lbrynet/schema/claim.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/stream_manager.py
  lbrynet/testcase.py
  tests/integration/test_file_commands.py
  tests/integration/test_streaming.py
Labels: area: database, area: files, type: fixup

#2100 DHT junction fixes for cases that can lock up
  lbrynet/dht/protocol/async_generator_junction.py
  lbrynet/dht/protocol/iterative_find.py
  tests/unit/dht/protocol/test_async_gen_junction.py
Labels: area: DHT, type: bug

#2102 Set a shutdown timeout for TCPSite to avoid hanging on exit
  lbrynet/extras/daemon/Daemon.py
Labels: area: api, type: improvement

#2048 Adjust default max_connections_per_download and peer_connect_timeout settings
  lbrynet/conf.py
Labels: area: config

#2104 correctly format lat/long and fee amounts in JSON RPC response
  lbrynet/schema/attrs.py
  lbrynet/schema/claim.py
  tests/integration/test_claim_commands.py
Labels: area: api, type: improvement

#2105 fix store content fee
  lbrynet/extras/daemon/storage.py
Labels: area: database, type: fixup

#2106 added logging to `publish` command
  lbrynet/extras/daemon/Daemon.py
Labels: area: api, type: improvement

#2107 fix stream_update failing on metadata only updates for files we don't have
  lbrynet/extras/daemon/Daemon.py
  lbrynet/extras/daemon/storage.py
  tests/integration/test_claim_commands.py
Labels: area: files, type: fixup

#2127 add `streaming_url` field to `File` api response type
  lbrynet/extras/daemon/json_response_encoder.py
  lbrynet/stream/managed_stream.py
Labels: area: files, type: improvement

#2128 add `streaming_server` and `streaming_get` settings to configure the interface/port of the media server and if it supports the `/get` endpoint
  docs/api.json
  lbrynet/conf.py
  lbrynet/extras/daemon/Daemon.py
  lbrynet/stream/managed_stream.py
  tests/integration/test_streaming.py
Labels: area: config, type: improvement

#2131 remove supports from resolve
  lbrynet/wallet/server/session.py
  tests/integration/test_chris45.py
Labels: area: wallet server, type: improvement

#2130 Fix updating refreshed announcements in the datastore
  lbrynet/dht/protocol/data_store.py
  lbrynet/dht/protocol/protocol.py
  tests/unit/dht/protocol/test_data_store.py
  tests/unit/stream/test_managed_stream.py
Labels: area: DHT, type: bug

#2138 fix save_file doc
  docs/api.json
  lbrynet/extras/daemon/Daemon.py
Labels: area: docs, type: bug

#2148 Fix resolve internals caching and persisting errors
  lbrynet/utils.py
  lbrynet/wallet/resolve.py
  tests/integration/test_resolve_command.py
Labels: area: claims, type: improvement

#2150 added zscore trending in wallet server
  lbrynet/wallet/server/block_processor.py
  lbrynet/wallet/server/db.py
  lbrynet/wallet/server/trending.py
  tests/unit/wallet/server/test_sqldb.py
Labels: area: wallet server, type: new feature

#2156 several minor wallet server fixes
  lbrynet/extras/daemon/json_response_encoder.py
  lbrynet/schema/compat.py
  lbrynet/wallet/server/db.py
Labels: area: wallet server, type: fixup

#2157 new script to verify wallet server database consistency against lbrycrd
  scripts/checktrie.py
Labels: area: wallet server, type: task

#2161 enforce min python version
  INSTALL.md
  setup.py
Labels: area: docs, type: improvement

#2167 fix startup error when single key account present in wallet
  lbrynet/wallet/ledger.py
Labels: area: wallet, type: bug

#2178 add a lru cache for decrypted blobs to minimize redownloading them, add `blob_lru_cache_size` to the config to set the cache size
  lbrynet/blob/blob_manager.py
  lbrynet/conf.py
  lbrynet/stream/downloader.py
  lbrynet/stream/managed_stream.py
  lbrynet/testcase.py
  lbrynet/utils.py
  tests/integration/test_streaming.py
Labels: area: blobs/files, type: improvement

#2180 fix false negative with file `completed` field
  lbrynet/stream/managed_stream.py
Labels: area: files, type: fixup
