Repository lbryio/lbry-sdk, pull requests merged in 2019-08, with the labels that each got.

#2358 Fixes comment docs & adds wallet component requirement on comment funcs
  lbry/lbry/extras/daemon/Daemon.py
Labels: area: commenting, type: improvement

#2379 Add `connected_servers` field to wallet status and improve analytics for wallet related download errors
  lbry/lbry/extras/daemon/Components.py
  lbry/lbry/extras/daemon/Daemon.py
  lbry/lbry/extras/daemon/analytics.py
  lbry/lbry/stream/stream_manager.py
  lbry/tests/unit/stream/test_stream_manager.py
Labels: area: wallet, type: improvement

#2384 Faster file list
  lbry/lbry/stream/managed_stream.py
Labels: area: blobs/files, type: improvement

#2385 Blob exchange server timeouts
  lbry/lbry/blob_exchange/server.py
  lbry/tests/unit/blob_exchange/test_transfer_blob.py
Labels: area: blob exchange, type: improvement

#2400 monitor wallet server block transitions and report if new block is excessively delayed
  lbry/lbry/wallet/server/session.py
  lbry/scripts/wallet_server_monitor.py
Labels: area: wallet server, type: new feature

#2402 bump `aioupnp` requirement to 0.0.14, fixes upnp errors blocking startup
  lbry/setup.py
Labels: area: network, type: improvement

#2401 UDP ping blob peers to prioritize those who can be connected to
  lbry/lbry/blob_exchange/client.py
  lbry/lbry/blob_exchange/downloader.py
  lbry/lbry/blob_exchange/server.py
  lbry/lbry/dht/node.py
  lbry/lbry/extras/daemon/Daemon.py
  lbry/tests/unit/blob_exchange/test_transfer_blob.py
Labels: area: downloads, type: improvement

#2398 Improve wallet server selection
  torba/tests/client_tests/unit/test_database.py
  torba/tests/client_tests/unit/test_ledger.py
  torba/torba/client/baseledger.py
  torba/torba/client/basenetwork.py
  torba/torba/rpc/jsonrpc.py
  torba/torba/rpc/session.py
  torba/torba/server/session.py
Labels: area: wallet, type: improvement

#2407 travis: remount /tmp as tmpfs
  .travis.yml
Labels: area: tests, type: fixup

#2397 fix unpack error known leftovers
  lbry/lbry/extras/daemon/json_response_encoder.py
  lbry/lbry/wallet/ledger.py
  lbry/lbry/wallet/resolve.py
  lbry/tests/integration/test_dht.py
  torba/tests/client_tests/unit/test_headers.py
  torba/torba/client/baseheader.py
  torba/torba/client/baseledger.py
Labels: area: wallet, type: bug

#2413 metrics reporting fix for wallet servers
  lbry/lbry/wallet/server/metrics.py
  lbry/lbry/wallet/server/session.py
Labels: area: wallet server, type: bug

#2434 fix intermittent bug where claim metadata was cleared out
  lbry/lbry/extras/daemon/json_response_encoder.py
Labels: area: api, type: bug
