Repository lbryio/lbry-sdk, pull requests merged in 2019-06, with the labels that each got.

#2202 `start` command accepts server lists arguments by passing `--server-argument=` multiple times.
  lbrynet/conf.py
  tests/unit/test_conf.py
Labels: area: cli, type: improvement

#2203 `claim search` filtering by `claim_type`/`stream_types`/`media_types`
  lbrynet/extras/daemon/Daemon.py
  lbrynet/wallet/server/db.py
  tests/integration/test_claim_commands.py
Labels: area: wallet server, type: fixup

#2196 add connection and bandwidth status
  lbrynet/blob/blob_manager.py
  lbrynet/blob_exchange/client.py
  lbrynet/blob_exchange/downloader.py
  lbrynet/blob_exchange/server.py
  lbrynet/connection_manager.py
  lbrynet/extras/daemon/Components.py
  lbrynet/extras/daemon/Daemon.py
Labels: area: blob exchange, type: new feature

#2211 pin aioupnp requirement to 0.0.12
  setup.py
Labels: area: packaging, type: improvement

#2214 better handle claims which fail to decode
  lbrynet/wallet/database.py
  lbrynet/wallet/transaction.py
Labels: area: claims, type: improvement

#2216 fix connections status raising an error during startup
  lbrynet/extras/daemon/Components.py
Labels: type: fixup

#2217 fix handling chunked reflector server responses
  lbrynet/stream/reflector/client.py
  lbrynet/stream/reflector/server.py
  tests/unit/stream/test_reflector.py
Labels: area: reflector, type: fixup

#2247 paginated deterministically shuffled find_value
  .pylintrc
  lbrynet/dht/constants.py
  lbrynet/dht/protocol/protocol.py
  lbrynet/dht/serialization/bencoding.py
  lbrynet/dht/serialization/datagram.py
  tests/unit/dht/protocol/test_protocol.py
  tests/unit/dht/serialization/test_datagram.py
  tests/unit/dht/test_blob_announcer.py
Labels: area: DHT, type: improvement

#2248 update wallet servers
  lbrynet/conf.py
Labels: type: fixup
