Repository lbryio/lbry-sdk, pull requests merged in 2019-07, with the labels that each got.

#2275 add `track_bandwidth` config setting to disable bandwidth usage in `status`, add `total_sent` and `total_received` fields to connection status
  lbry/lbry/blob/blob_manager.py
  lbry/lbry/conf.py
  lbry/lbry/connection_manager.py
Labels: area: config, type: improvement

#2273 Fix wallet server session bloat from unhandled socket errors
  lbry/tests/integration/test_wallet_server_sessions.py
  torba/torba/rpc/jsonrpc.py
  torba/torba/server/daemon.py
  torba/torba/server/env.py
  torba/torba/server/peer.py
  torba/torba/server/peers.py
  torba/torba/server/server.py
  torba/torba/server/session.py
Labels: area: wallet server, type: improvement

#2287 use utils.aiohttp for comments
  lbry/lbry/extras/daemon/comment_client.py
Labels: area: commenting, type: fixup

#2286 Fixes corner case on comment validation for pending channel
  lbry/lbry/extras/daemon/comment_client.py
Labels: area: commenting, type: fixup

#2298 added `--no-totals` argument to `claim search`
  lbry/lbry/extras/daemon/Daemon.py
  lbry/lbry/schema/result.py
  lbry/lbry/wallet/server/db.py
  lbry/tests/integration/test_claim_commands.py
Labels: area: api, type: improvement

#2294 fixed issue where sqlite threw "too many sql variables" error
  torba/tests/client_tests/unit/test_database.py
  torba/torba/client/basedatabase.py
Labels: area: database, type: bug

#2303 `claim search` uses different tag filtering approaches depending on query type
  lbry/lbry/wallet/server/db.py
  torba/torba/client/basedatabase.py
Labels: area: wallet server, type: improvement

#2304 tx parsing speedup and faster wallet sync
  lbry/lbry/wallet/database.py
  torba/torba/client/basedatabase.py
  torba/torba/client/baseledger.py
  torba/torba/client/basetransaction.py
Labels: area: wallet, type: improvement

#2306 fix for travis windows build
  .travis.yml
Labels: area: packaging, type: bug

#2347 save channel keys into wallet before broadcasting
  lbry/lbry/extras/daemon/Daemon.py
Labels: area: claims, type: improvement

#2348 Probe if peers can be connected to during blob downloads to more quickly skip bad peers
  lbry/lbry/blob_exchange/client.py
  lbry/lbry/blob_exchange/downloader.py
Labels: area: downloads, type: improvement

#2355 added index for claim_type searches
  lbry/lbry/wallet/server/db/writer.py
Labels: area: wallet server, type: improvement
