Repository lbryio/lbry-sdk, pull requests merged in 2019-01, with the labels that each got.

#1741 added `utxo_release` command
  lbrynet/extras/daemon/Daemon.py
  lbrynet/extras/wallet/account.py
  lbrynet/extras/wallet/database.py
  tests/integration/wallet/test_commands.py
Labels: area: api, type: new feature

#1734 added `lbrynet4.lbry.io` to list of default DHT nodes
  lbrynet/conf.py
Labels: area: config, type: improvement

#1748 include file extension in media-type metadata for unknown media types
  lbrynet/extras/daemon/Daemon.py
  lbrynet/extras/daemon/Publisher.py
  lbrynet/extras/daemon/mime_types.py
Labels: area: blobs/files, type: improvement

#1751 fixed database migration (5 to 6) encoding
  lbrynet/extras/daemon/migrator/migrate5to6.py
Labels: area: database, type: bug

#1750 fixed saving claims with certificate id
  lbrynet/extras/daemon/storage.py
Labels: area: database, type: bug

#1760 fix unavailable download directory
  lbrynet/extras/daemon/Daemon.py
Labels: area: blobs/files, type: bug

#1749 added additional fields to uri parser to return consistent results
  lbrynet/extras/daemon/Daemon.py
  lbrynet/extras/wallet/server/session.py
  lbrynet/schema/uri.py
  tests/unit/schema/test_lbryschema.py
Labels: area: wallet, type: refactor

#1764 add `.m4v` video format type
  lbrynet/extras/daemon/mime_types.py
Labels: area: blobs/files, type: new feature

#1767 added note that wallet needs to be unlocked to decrypt
  lbrynet/extras/daemon/Daemon.py
Labels: area: api, type: improvement

#1763 orchstr8 docker for lbry
  .dockerignore
  scripts/Dockerfile.lbry_orchstr8
Labels: area: packaging, type: new feature

#1777 fixed bytes vs str error in migrate5to6 script
  lbrynet/extras/daemon/migrator/migrate5to6.py
Labels: area: database, type: bug

#1784 removed previously deprecated commands `wallet_prefill_addresses`, `wallet_unused_address`, `wallet_new_address`, `wallet_list`, `wallet_public_key`, `wallet_is_address_mine`, `wallet_encrypt`, `wallet_decrypt`, `wallet_unlock`, `stop` and `claim_renew`
  lbrynet/extras/daemon/Daemon.py
Labels: area: api, type: refactor

#1802 add step to build wallet server images when a release gets tagged
  .travis.yml
Labels: type: task

#1809 fix blob server protocol factory
  lbrynet/blob_exchange/server.py
  tests/unit/blob_exchange/test_transfer_blob.py
  tests/unit/stream/test_downloader.py
Labels: type: fixup

#1810 async reflector
  lbrynet/extras/daemon/Components.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/reflector/__init__.py
  lbrynet/stream/reflector/client.py
  lbrynet/stream/reflector/server.py
  lbrynet/stream/stream_manager.py
  tests/unit/dht/test_async_gen_junction.py
  tests/unit/stream/test_reflector.py
Labels: type: refactor

#1822 Update settings
  lbrynet/blob_exchange/downloader.py
  lbrynet/conf.py
  lbrynet/dht/blob_announcer.py
  lbrynet/dht/node.py
  lbrynet/extras/daemon/Components.py
  lbrynet/extras/daemon/Daemon.py
  lbrynet/extras/daemon/analytics.py
  lbrynet/extras/daemon/storage.py
  lbrynet/stream/downloader.py
  lbrynet/stream/reflector/client.py
  lbrynet/stream/reflector/server.py
  lbrynet/stream/stream_manager.py
  tests/integration/wallet/test_commands.py
  tests/unit/lbrynet_daemon/test_Daemon.py
Labels: area: config, type: fixup

#1824 fix timeout error
  lbrynet/dht/protocol/async_generator_junction.py
  lbrynet/dht/protocol/protocol.py
  lbrynet/extras/daemon/Daemon.py
Labels: area: DHT, type: fixup

#1825 Fix hanging download
  lbrynet/blob_exchange/client.py
  lbrynet/extras/daemon/Components.py
  lbrynet/stream/downloader.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/stream_manager.py
  scripts/download_blob_from_peer.py
  tests/unit/dht/test_async_gen_junction.py
Labels: area: DHT, area: blobs/files, type: fixup

#1830 Dht fixes
  lbrynet/dht/node.py
  lbrynet/dht/protocol/iterative_find.py
  lbrynet/extras/daemon/storage.py
Labels: area: DHT, type: fixup

#1831 Download and publish fixes
  lbrynet/blob_exchange/client.py
  lbrynet/blob_exchange/downloader.py
  lbrynet/blob_exchange/server.py
  lbrynet/conf.py
  lbrynet/dht/node.py
  lbrynet/extras/cli.py
  lbrynet/extras/daemon/Components.py
  lbrynet/extras/daemon/Daemon.py
  lbrynet/extras/daemon/storage.py
  lbrynet/stream/assembler.py
  lbrynet/stream/downloader.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/stream_manager.py
  lbrynet/utils.py
  scripts/download_blob_from_peer.py
  scripts/repair_0_31_1_db.py
  scripts/time_to_first_byte.py
  tests/integration/wallet/test_commands.py
  tests/unit/blob_exchange/test_transfer_blob.py
  tests/unit/stream/test_assembler.py
  tests/unit/stream/test_downloader.py
  tests/unit/stream/test_reflector.py
Labels: area: api, area: blob exchange, area: config, area: downloads, type: fixup, type: improvement, type: refactor
