Repository lbryio/lbry-sdk, pull requests merged in 2019-09, with the labels that each got.

#2418 sync and connection issues
  lbry/lbry/wallet/manager.py
  lbry/lbry/wallet/server/db/writer.py
  lbry/lbry/wallet/server/session.py
  lbry/tests/integration/test_wallet_server_sessions.py
  torba/tests/client_tests/integration/test_network.py
  torba/tests/client_tests/integration/test_transactions.py
  torba/tests/client_tests/unit/test_ledger.py
  torba/torba/client/basedatabase.py
  torba/torba/client/baseledger.py
  torba/torba/client/basenetwork.py
  torba/torba/orchstr8/node.py
  torba/torba/server/db.py
  torba/torba/server/storage.py
Labels: area: wallet server, type: improvement

#2451 bugfixes for wallet client network rare edge case where it switches to a server about to go down
  torba/torba/client/basenetwork.py
Labels: area: wallet, type: improvement

#2458 default wallet server to LBC coin
  torba/torba/server/cli.py
Labels: area: wallet server

#2466 add Flac mime type
  lbry/lbry/schema/mime_types.py
Labels: area: files, type: improvement

#2455 Fix docopt for `claim_search`
  lbry/lbry/extras/daemon/Daemon.py
Labels: area: cli, type: improvement

#2473 Check invalid names against updated regex so it matches the app
  lbry/lbry/schema/url.py
  lbry/tests/unit/schema/test_url.py
Labels: area: claims, type: improvement

#2474 Handle claim_name as a string
  lbry/lbry/extras/cli.py
  lbry/tests/unit/test_cli.py
Labels: area: cli, type: bug

#2481 Fix new pylint
  lbry/lbry/blob_exchange/client.py
  lbry/lbry/extras/cli.py
  lbry/lbry/extras/daemon/migrator/dbmigrator.py
  lbry/lbry/extras/daemon/migrator/migrate5to6.py
  lbry/lbry/extras/daemon/storage.py
  lbry/lbry/extras/system_info.py
  lbry/lbry/wallet/server/db/reader.py
  torba/torba/client/baseaccount.py
  torba/torba/client/basedatabase.py
  torba/torba/client/basetransaction.py
  torba/torba/coin/bitcoinsegwit.py
Labels: type: fixup

#2479 handle intermediate state on wallet client sessions
  torba/tests/client_tests/integration/test_network.py
  torba/torba/client/basenetwork.py
Labels: area: wallet, type: bug

#2484 change trending window to 6 hours
  lbry/lbry/wallet/server/db/trending.py
Labels: area: wallet server, type: improvement

#2493 fix for wallet_remove command
  lbry/lbry/extras/daemon/Daemon.py
Labels: area: api, type: bug
