Repository lbryio/lbry-sdk, pull requests merged in 2019-02, with the labels that each got.

#1834 remove blob request asyncio.Lock
  lbrynet/blob_exchange/client.py
Labels: area: blob exchange, type: refactor

#1833 Fix publish when making an update with an existing stream
  lbrynet/extras/daemon/Daemon.py
Labels: area: api, type: fixup

#1835 Remove peer manager lock
  lbrynet/dht/peer.py
  lbrynet/dht/protocol/protocol.py
Labels: area: DHT, type: refactor

#1838 Fix publishing an update where we don't have the previous stream
  lbrynet/extras/daemon/Daemon.py
  lbrynet/stream/stream_manager.py
Labels: area: api, area: files, type: fixup

#1839 faster stream manager startup
  lbrynet/stream/stream_manager.py
Labels: area: api, type: improvement

#1841 General fixes downloader
  lbrynet/blob/blob_file.py
  lbrynet/blob/writer.py
  lbrynet/blob_exchange/downloader.py
  lbrynet/extras/daemon/Components.py
  lbrynet/extras/daemon/Daemon.py
  lbrynet/stream/assembler.py
  lbrynet/stream/downloader.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/stream_manager.py
  tests/unit/stream/test_downloader.py
Labels: area: blob exchange, area: blobs/files, area: downloads, type: fixup

#1840 close blob server transport on sendfile failing
  lbrynet/blob_exchange/server.py
Labels: area: blob exchange, type: fixup

#1844 Reassemble when deleted from downloads
  lbrynet/blob_exchange/server.py
  lbrynet/dht/blob_announcer.py
  lbrynet/dht/node.py
  lbrynet/dht/protocol/iterative_find.py
  lbrynet/dht/protocol/protocol.py
  lbrynet/extras/daemon/Daemon.py
  lbrynet/extras/daemon/storage.py
  lbrynet/stream/assembler.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/stream_manager.py
Labels: area: api, area: downloads, area: files

#1847 add re-reflect task to stream manager, add concurrent_reflector_uploads to config
  lbrynet/conf.py
  lbrynet/stream/reflector/client.py
  lbrynet/stream/stream_manager.py
Labels: area: config, area: reflector

#1848 Fix setting blob announce time
  lbrynet/dht/blob_announcer.py
  lbrynet/extras/daemon/storage.py
  lbrynet/stream/stream_manager.py
Labels: area: database, type: fixup

#1849 Fix connection status
  lbrynet/extras/daemon/Daemon.py
  lbrynet/stream/stream_manager.py
  lbrynet/utils.py
Labels: area: api, type: fixup

#1850 Properly resume streams and fixup with statement
  lbrynet/stream/assembler.py
  lbrynet/stream/stream_manager.py
Labels: area: downloads, type: fixup

#1852 refactor reflect to close protocol
  lbrynet/stream/managed_stream.py
Labels: area: reflector, type: fixup

#1854 fix trying downloading from oneself, prune querying peer from findValue results
  lbrynet/dht/node.py
  lbrynet/dht/protocol/iterative_find.py
  lbrynet/dht/protocol/protocol.py
  lbrynet/dht/protocol/routing_table.py
Labels: area: DHT, type: fixup

#1857 Handle invalid data and fix cancel blob request
  lbrynet/blob_exchange/client.py
  lbrynet/blob_exchange/downloader.py
Labels: area: blob exchange, type: fixup

#1858 Fix blob sendfile
  lbrynet/blob/blob_file.py
Labels: area: blob exchange, type: fixup

#1859 handle and log if downloading from bad sendfile implementations
  lbrynet/blob_exchange/client.py
Labels: area: blob exchange, type: fixup

#1860 Fix setting blob completed and next announce time
  lbrynet/blob/blob_manager.py
  lbrynet/extras/cli.py
  lbrynet/extras/daemon/storage.py
  lbrynet/stream/downloader.py
  lbrynet/stream/managed_stream.py
Labels: area: database, type: fixup

#1862 adds announce tests on stream creation/assemble, refactor calls to set announce
  lbrynet/blob/blob_file.py
  lbrynet/blob/blob_manager.py
  lbrynet/extras/daemon/storage.py
  lbrynet/stream/assembler.py
  lbrynet/stream/downloader.py
  lbrynet/stream/managed_stream.py
  tests/unit/stream/test_assembler.py
Labels: area: DHT, area: blob exchange, area: database, type: fixup

#1868 format error dict on get
  lbrynet/extras/daemon/Daemon.py
Labels: area: api, type: fixup

#1866 refactor blob.close to be non-async, speed up deleting blobs and streams
  lbrynet/blob/blob_file.py
  lbrynet/blob/blob_manager.py
  lbrynet/blob_exchange/downloader.py
  lbrynet/dht/protocol/protocol.py
  lbrynet/extras/daemon/Components.py
  lbrynet/extras/daemon/Daemon.py
  lbrynet/stream/assembler.py
  lbrynet/stream/descriptor.py
  lbrynet/stream/downloader.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/stream_manager.py
  tests/unit/lbrynet_daemon/test_ExchangeRateManager.py
  tests/unit/stream/test_downloader.py
  tests/unit/stream/test_stream_manager.py
Labels: area: files, type: fixup

#1873 test incomplete streams, respect real length, delete on incomplete as…
  lbrynet/blob/blob_file.py
  lbrynet/stream/assembler.py
  lbrynet/stream/descriptor.py
  tests/unit/stream/test_assembler.py
Labels: type: fixup

#1889 Refactor peer scoring and maintain connections to fix stuck downloads, remove locking from ping queue
  lbrynet/blob/blob_file.py
  lbrynet/blob_exchange/client.py
  lbrynet/blob_exchange/downloader.py
  lbrynet/conf.py
  lbrynet/dht/node.py
  lbrynet/dht/protocol/protocol.py
  lbrynet/stream/assembler.py
  lbrynet/stream/downloader.py
  tests/unit/blob_exchange/test_transfer_blob.py
Labels: area: downloads, type: improvement

#1892 Improve startup time
  lbrynet/blob/blob_file.py
  lbrynet/blob/blob_manager.py
  lbrynet/blob_exchange/client.py
  lbrynet/extras/cli.py
  lbrynet/extras/daemon/storage.py
  lbrynet/stream/stream_manager.py
  scripts/time_to_first_byte.py
Labels: area: database, type: improvement

#1894 fix max_key_fee not being followed
  lbrynet/conf.py
  lbrynet/extras/daemon/exchange_rate_manager.py
  lbrynet/stream/stream_manager.py
  tests/unit/lbrynet_daemon/test_ExchangeRateManager.py
  tests/unit/stream/test_stream_manager.py
Labels: area: config, type: fixup

#1906 database migration bug related to passing conf argument
  lbrynet/extras/daemon/Components.py
Labels: area: database, type: bug

#1909 renamed resolve argument url to urls
  lbrynet/extras/daemon/Daemon.py
Labels: area: api, type: fixup

#1905 Faster file delete
  lbrynet/blob/blob_file.py
  lbrynet/blob/blob_manager.py
  lbrynet/extras/daemon/storage.py
  lbrynet/stream/stream_manager.py
  tests/integration/test_file_commands.py
Labels: area: database, type: improvement

#1922 supress invalid token error to debug
  lbrynet/dht/protocol/protocol.py
Labels: type: fixup

#1926 Fix p2p ignoring good peers
  lbrynet/blob_exchange/client.py
  lbrynet/blob_exchange/downloader.py
  lbrynet/stream/downloader.py
Labels: area: downloads, type: improvement

#1925 fix application/x-ext mime types
  lbrynet/extras/daemon/mime_types.py
  tests/unit/lbrynet_daemon/test_mime_types.py
Labels: area: files, type: fixup

#1928 listen on internal port instead of upnp redirect
  lbrynet/extras/daemon/Components.py
Labels: type: fixup

#1932 Fix blob_list for sd_hash including stream terminator
  lbrynet/extras/daemon/Daemon.py
Labels: area: api, type: fixup

#1933 remove invalid reflector_component test config
  tests/unit/lbrynet_daemon/test_Daemon.py
Labels: area: tests, type: fixup

#1935 downloading header from S3 correctly tracks progress
  lbrynet/extras/daemon/Components.py
Labels: area: api, type: bug

#1938 fix KBucket.key_in_range
  lbrynet/dht/protocol/routing_table.py
  tests/unit/dht/routing/test_routing_table.py
Labels: area: DHT, type: bug

#1939 refactor file_name and full_path as it can be None, fix missing await, stop using blob_manager.storage on stream_manager and use your own
  lbrynet/stream/managed_stream.py
  lbrynet/stream/stream_manager.py
Labels: area: files, type: bug, type: fixup, type: refactor

#1942 add split_buckets_under_index config setting for seed nodes
  lbrynet/conf.py
  lbrynet/dht/constants.py
  lbrynet/dht/node.py
  lbrynet/dht/protocol/protocol.py
  lbrynet/dht/protocol/routing_table.py
  lbrynet/extras/daemon/Components.py
Labels: area: config, type: new feature

#1944 fix seed node startup
  lbrynet/dht/node.py
  scripts/time_to_first_byte.py
Labels: area: DHT, type: fixup

#1948 Test and fix edge cases for adding peers to routing
  lbrynet/dht/constants.py
  lbrynet/dht/protocol/protocol.py
  lbrynet/dht/protocol/routing_table.py
  tests/unit/dht/protocol/test_protocol.py
  tests/unit/dht/routing/test_kbucket.py
Labels: area: DHT, type: fixup

#1949 fix cases where buckets could be unjoined after removing a peer
  lbrynet/dht/protocol/protocol.py
Labels: area: DHT, type: fixup

#1950 Fix slow ping queue shutdown
  lbrynet/dht/protocol/protocol.py
Labels: area: DHT, type: fixup

#1951 Fix invalid blob decode startup
  lbrynet/blob/blob_file.py
  lbrynet/stream/descriptor.py
  tests/integration/test_file_commands.py
  tests/unit/stream/test_stream_descriptor.py
Labels: area: blobs/files, type: bug

#1946 lowercase/stripped comparison for known types
  lbrynet/extras/daemon/mime_types.py
  tests/unit/lbrynet_daemon/test_mime_types.py
Labels: type: fixup

#1959 pin jsonschema version to 2.6.0
  setup.py
Labels: type: fixup

#1952 stop trapping CancelledError
  lbrynet/blob_exchange/downloader.py
  lbrynet/dht/node.py
  lbrynet/dht/protocol/iterative_find.py
  lbrynet/extras/daemon/Daemon.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/reflector/server.py
  lbrynet/stream/stream_manager.py
Labels: area: asyncio rewrite, type: bug

#1965 fix ssl errors, use certifi to make ssl contexts
  lbrynet/extras/daemon/Components.py
  lbrynet/extras/daemon/analytics.py
  lbrynet/extras/daemon/exchange_rate_manager.py
  lbrynet/extras/daemon/loggly_handler.py
  lbrynet/utils.py
  setup.py
Labels: area: packaging, type: bug
