Repository lbryio/lbry-sdk, pull requests merged in 2019-04, with the labels that each got.

#2014 time to first byte script
  scripts/time_to_first_byte.py
Labels: area: tests, type: bug

#2012 added mapping of stream type to media file extensions
  lbrynet/schema/mime_types.py
Labels: area: files, type: improvement

#2022 Fixes issue causing packages incompatible with torba getting installed [attrs==18.2.0]
  setup.py
Labels: area: packaging, type: improvement

#2015 fix set_build.py type on mac by running it with python3 explicitely
  .travis.yml
Labels: area: packaging, type: bug

#2038 renamed txo sub_type to value_type in txo json encoder output
  lbrynet/extras/daemon/json_response_encoder.py
Labels: area: api, type: improvement

#2039 add new encoder fields on resolve so app can use them
  lbrynet/wallet/resolve.py
Labels: area: api, type: improvement

#2042 ability to override the file name, hash and size when updating a stream
  lbrynet/extras/daemon/Daemon.py
  lbrynet/schema/claim.py
  tests/integration/test_claim_commands.py
Labels: area: api, type: improvement

#2043 add lbry:// to permanent_url response field
  lbrynet/wallet/transaction.py
Labels: area: api, type: improvement

#2020 Support HTTP 206 partial content requests for streaming downloads
  example_daemon_settings.yml
  lbrynet/blob/blob_file.py
  lbrynet/blob/blob_manager.py
  lbrynet/blob/writer.py
  lbrynet/blob_exchange/client.py
  lbrynet/blob_exchange/downloader.py
  lbrynet/blob_exchange/server.py
  lbrynet/conf.py
  lbrynet/dht/protocol/iterative_find.py
  lbrynet/dht/protocol/protocol.py
  lbrynet/error.py
  lbrynet/extras/daemon/Components.py
  lbrynet/extras/daemon/Daemon.py
  lbrynet/extras/daemon/storage.py
  lbrynet/stream/assembler.py
  lbrynet/stream/descriptor.py
  lbrynet/stream/downloader.py
  lbrynet/stream/managed_stream.py
  lbrynet/stream/reflector/client.py
  lbrynet/stream/reflector/server.py
  lbrynet/stream/stream_manager.py
  lbrynet/testcase.py
  lbrynet/utils.py
  scripts/download_blob_from_peer.py
  scripts/generate_json_api.py
  scripts/standalone_blob_server.py
  tests/dht_mocks.py
  tests/integration/test_claim_commands.py
  tests/integration/test_file_commands.py
  tests/integration/test_streaming.py
  tests/unit/blob/test_blob_file.py
  tests/unit/blob/test_blob_manager.py
  tests/unit/blob_exchange/test_transfer_blob.py
  tests/unit/core/test_utils.py
  tests/unit/database/test_SQLiteStorage.py
  tests/unit/dht/protocol/test_data_store.py
  tests/unit/dht/test_blob_announcer.py
  tests/unit/stream/test_assembler.py
  tests/unit/stream/test_downloader.py
  tests/unit/stream/test_managed_stream.py
  tests/unit/stream/test_reflector.py
  tests/unit/stream/test_stream_descriptor.py
  tests/unit/stream/test_stream_manager.py
Labels: area: api, type: new feature

#2054 install uvloop on wallet server docker image and default to it
  scripts/Dockerfile.wallet_server
Labels: area: wallet server, type: improvement

#2045 time-to-first-byte script fixes
  lbrynet/extras/cli.py
  lbrynet/extras/daemon/client.py
  scripts/time_to_first_byte.py
Labels: area: devops, type: bug

#2056 added `--clear_fee` ability to `stream update` command
  lbrynet/extras/daemon/Daemon.py
  lbrynet/schema/claim.py
  tests/integration/test_claim_commands.py
Labels: area: api, type: new feature

#2059 updating stream claim with new file now correctly updates file list by removing old file
  lbrynet/extras/daemon/Daemon.py
  tests/integration/test_claim_commands.py
Labels: area: blobs/files, type: bug

#2060 fixed signing streams using `--channel_name` argument
  lbrynet/extras/daemon/Daemon.py
  tests/integration/test_claim_commands.py
Labels: area: api, type: bug

#2061 fixed `--preview` mode on `stream_create`/`stream_update`
  lbrynet/extras/cli.py
  lbrynet/extras/daemon/Daemon.py
  tests/integration/test_claim_commands.py
Labels: area: api, type: bug

#2062 added `timestamp` field to transaction output results from JSON RPC calls
  lbrynet/extras/daemon/json_response_encoder.py
Labels: area: api, type: improvement
