Repository lbryio/lbry-sdk, pull requests merged in 2019-11, with the labels that each got.

#2552 Add optional extensions to DHT datagram format
  lbry/lbry/dht/serialization/datagram.py
  lbry/tests/unit/dht/serialization/test_datagram.py
Labels: area: DHT, type: new feature

#2612 wallet server: send correct server version (sdk version now)
  lbry/lbry/wallet/server/session.py
  lbry/tests/integration/test_wallet_server_sessions.py
  torba/torba/server/session.py
Labels: area: wallet server, type: improvement

#2623 bump aioupnp to 0.0.16, fixes UPnP support for TP-Link routers
  lbry/setup.py
Labels: area: network, type: improvement

#2624 stop signing support TXs too many times
  lbry/lbry/extras/daemon/Daemon.py
Labels: area: wallet, type: improvement

#2633 added `settings_clear` command to reset a setting to its default value
  lbry/lbry/extras/daemon/Daemon.py
  lbry/tests/integration/test_other_commands.py
Labels: area: api, type: new feature

#2635 adds wallet server information to `status` command
  lbry/lbry/extras/daemon/Components.py
Labels: area: api, type: improvement

#2642 upgrade SDK to use lbrycrd v0.17.3.2
  lbry/lbry/wallet/__init__.py
Labels: area: wallet server, type: improvement
