Repository lbryio/lbry-sdk, pull requests merged in 2019-10, with the labels that each got.

#2497 bug fixes related to cross-account / wallet operations
  lbry/lbry/extras/daemon/Daemon.py
  lbry/tests/integration/test_claim_commands.py
Labels: area: wallet, type: bug

#2521 fix resolving fixed peers from an ipv6 connection
  lbry/lbry/dht/peer.py
  lbry/lbry/utils.py
Labels: area: downloads, type: bug

#2487 handle error if range request transport is reset
  lbry/lbry/stream/managed_stream.py
Labels: area: media server, type: fixup

#2527 only do trending calculations near the tip of the chain
  lbry/lbry/wallet/server/db/trending.py
  lbry/lbry/wallet/server/db/writer.py
Labels: area: wallet server, type: improvement

#2533 added `wallet balance` command
  lbry/lbry/extras/daemon/Daemon.py
  lbry/lbry/wallet/account.py
  lbry/lbry/wallet/dewies.py
  lbry/lbry/wallet/ledger.py
  lbry/tests/integration/test_transaction_commands.py
Labels: area: api, type: new feature

#2534 `utxo release` applies to all accounts in wallet
  lbry/lbry/extras/daemon/Daemon.py
Labels: area: api, type: improvement

#2538 added `wallet send` command
  lbry/lbry/extras/daemon/Daemon.py
Labels: area: api, type: new feature

#2562 `publish` checks all accounts for claim before forwarding to `stream_create`/`stream_update`
  lbry/lbry/extras/daemon/Daemon.py
Labels: area: api, type: bug

#2566 fix for encrypted wallet with import read-only channel accounts
  lbry/tests/integration/test_wallet_commands.py
  torba/tests/client_tests/unit/test_account.py
  torba/torba/client/baseaccount.py
Labels: area: wallet, type: bug

#2577 don't error if blank password was set previously
  torba/torba/client/wallet.py
Labels: area: wallet, type: improvement

#2578 fix bug with resolve and conflicting `claim_id` segments
  lbry/lbry/wallet/server/db/reader.py
  lbry/tests/integration/test_resolve_command.py
  lbry/tests/unit/wallet/server/test_sqldb.py
Labels: area: discovery, type: bug

#2555 refactored logging configuration and added more tests
  lbry/lbry/extras/cli.py
  lbry/lbry/extras/daemon/loggly_handler.py
  lbry/tests/unit/test_cli.py
Labels: area: config, type: refactor

#2588 faster startup, bump aioupnp -> 0.0.15
  lbry/setup.py
Labels: area: network, type: improvement

#2589 fix 11to12 migration typo
  lbry/lbry/extras/daemon/migrator/dbmigrator.py
  lbry/lbry/extras/daemon/migrator/migrate11to12.py
Labels: area: database, type: fixup

#2593 daemon transaction sync bug fix, check `txo.has_address` before calling `txo.get_address()`
  torba/torba/client/basedatabase.py
  torba/torba/client/basetransaction.py
Labels: area: wallet, type: bug

#2594 remove bandwidth and subscriptions limits from wallet server
  torba/torba/server/session.py
Labels: area: wallet server, type: improvement
