Repository lbryio/lbry-sdk, pull requests merged in 2020-09, with the labels that each got.

#3034 misc fixes
  Makefile
  lbry/blockchain/lbrycrd.py
  lbry/cli.py
  lbry/service/api.py
  lbry/service/daemon.py
  setup.cfg
  tests/integration/service/test_daemon.py
Labels: type: fixup

#3036 fix doc generator for docopt edge cases
  lbry/service/api.py
  lbry/service/metadata.py
  lbry/service/parser.py
  tests/unit/service/test_parser.py
Labels: area: docs, type: bug

#3044 pin tqdm and fix ovrride
  lbry/console.py
  setup.py
Labels: type: fixup

#3040 Synchronizer: wait for lbrycrd to start if its not ready, instead of raising
  lbry/blockchain/lbrycrd.py
  lbry/blockchain/sync/synchronizer.py
  tests/integration/blockchain/test_blockchain.py
Labels: area: other, type: improvement

#3039 Include enough information in resolve protobuf so its possible to verify signatures
  lbry/blockchain/database.py
  lbry/blockchain/script.py
  lbry/blockchain/sync/claims.py
  lbry/blockchain/sync/synchronizer.py
  lbry/blockchain/util.py
  lbry/db/constants.py
  lbry/db/queries/resolve.py
  lbry/db/queries/search.py
  lbry/db/queries/txio.py
  lbry/db/query_context.py
  lbry/db/tables.py
  lbry/schema/result.py
  lbry/service/daemon.py
  lbry/testcase.py
  tests/integration/blockchain/test_blockchain.py
  tests/unit/blockchain/test_transaction.py
Labels: area: database, type: bug

#3050 add indexes for `any_languages` argument to `claim_search`
  lbry/wallet/server/block_processor.py
  lbry/wallet/server/db/common.py
  lbry/wallet/server/db/reader.py
  lbry/wallet/server/db/writer.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: wallet server, type: improvement

#3045 add forward compatibility for byte datagram keys
  lbry/dht/serialization/datagram.py
  tests/unit/dht/serialization/test_datagram.py
Labels: area: DHT, type: improvement
