Repository lbryio/lbry-sdk, pull requests merged in 2020-08, with the labels that each got.

#3015 added support for using the new SDK for `resolve` and `claim_search` by passing `--new_sdk_server`
  lbry/extras/daemon/daemon.py
  lbry/wallet/ledger.py
  lbry/wallet/network.py
Labels: area: api, type: new feature

#3016 release reserved outputs on startup
  lbry/wallet/database.py
  lbry/wallet/ledger.py
Labels: area: wallet, type: improvement

#3022 Add webvtt mime type ( subtitles, captions )
  lbry/schema/mime_types.py
Labels: area: files, type: improvement

#3028 added `--limit_claims_per_channel` argument to `claim_search` to only return up to the specified number of claims per channel
  lbry/extras/daemon/daemon.py
  lbry/schema/result.py
  lbry/wallet/server/db/reader.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature
