Repository lbryio/lbry-sdk, pull requests merged in 2020-05, with the labels that each got.

#2937 fix database lockup and add prometheus db metrics
  lbry/extras/daemon/daemon.py
  lbry/prometheus.py
  lbry/utils.py
  lbry/wallet/database.py
  lbry/wallet/rpc/session.py
  lbry/wallet/server/block_processor.py
  lbry/wallet/server/daemon.py
  lbry/wallet/server/prometheus.py
  lbry/wallet/server/server.py
  lbry/wallet/server/session.py
  tests/integration/blockchain/test_blockchain_reorganization.py
Labels: area: database, type: improvement

#2930 torrent support
  .gitlab-ci.yml
  Makefile
  lbry/extras/daemon/components.py
  lbry/extras/daemon/daemon.py
  lbry/extras/daemon/json_response_encoder.py
  lbry/extras/daemon/storage.py
  lbry/file/__init__.py
  lbry/file/file_manager.py
  lbry/file/source.py
  lbry/file/source_manager.py
  lbry/stream/downloader.py
  lbry/stream/managed_stream.py
  lbry/stream/stream_manager.py
  lbry/torrent/__init__.py
  lbry/torrent/session.py
  lbry/torrent/torrent.py
  lbry/torrent/torrent_manager.py
  setup.cfg
  tests/integration/datanetwork/test_file_commands.py
  tests/integration/datanetwork/test_streaming.py
  tests/integration/other/test_cli.py
  tests/unit/components/test_component_manager.py
  tests/unit/stream/test_managed_stream.py
  tests/unit/stream/test_reflector.py
  tests/unit/stream/test_stream_manager.py
  tox.ini
Labels: area: downloads, type: new feature

#2948 fix duplicate line on api doc
  lbry/extras/daemon/daemon.py
Labels: area: docs, type: bug

#2951 add `fixed_peers` setting to config
  lbry/conf.py
  lbry/extras/daemon/analytics.py
  lbry/stream/downloader.py
  lbry/testcase.py
  tests/unit/blob_exchange/test_transfer_blob.py
  tests/unit/stream/test_stream_manager.py
Labels: area: config, type: improvement

#2953 fix channel key generation blocking globally
  lbry/extras/daemon/daemon.py
  lbry/wallet/account.py
  lbry/wallet/database.py
  lbry/wallet/transaction.py
  tests/integration/blockchain/test_internal_transaction_api.py
  tests/unit/comments/test_comment_signing.py
  tests/unit/wallet/test_schema_signing.py
Labels: area: wallet, type: bug

#2954 add `uploading_to_reflector`, `is_fully_reflected`, `completed`, and `status` filter arguments to `file_list`, update to match all filters rather than any filters
  lbry/extras/daemon/daemon.py
  lbry/file/source_manager.py
  lbry/stream/managed_stream.py
  lbry/stream/reflector/client.py
  lbry/stream/stream_manager.py
Labels: area: files, type: improvement

#2955 fix node not being set on the downloader in some cases
  lbry/extras/daemon/daemon.py
  lbry/file/file_manager.py
  lbry/stream/managed_stream.py
  lbry/stream/stream_manager.py
Labels: area: downloads, type: bug

#2957 added `download_path` as a filter for `file_list` command
  lbry/extras/daemon/daemon.py
  lbry/file/source_manager.py
  lbry/stream/managed_stream.py
Labels: area: api, type: new feature

#2967 add `transaction_cache_size` to config
  lbry/conf.py
  lbry/dht/protocol/protocol.py
  lbry/wallet/ledger.py
  lbry/wallet/manager.py
  lbry/wallet/rpc/session.py
  lbry/wallet/server/block_processor.py
  lbry/wallet/server/session.py
  tests/unit/components/test_component_manager.py
Labels: area: wallet, type: improvement
