Repository lbryio/lbry-sdk, pull requests merged in 2020-06, with the labels that each got.

#2968 more aggressive video transcoding to reduce file sizes
  lbry/conf.py
Labels: area: files, type: improvement

#2966 add `allowed_origin` to config, by default no longer allow any requests which pass Origin in header
  lbry/conf.py
  lbry/extras/daemon/daemon.py
  lbry/extras/daemon/security.py
  tests/unit/lbrynet_daemon/test_allowed_origin.py
Labels: area: api, type: improvement

#2972 Improve wallet server address history cache and the rate of sent notifications
  lbry/wallet/rpc/session.py
  lbry/wallet/server/block_processor.py
  lbry/wallet/server/session.py
Labels: area: wallet server, type: bug

#2971 Speed up publish response time by not blocking on updating the content claim db
  lbry/extras/daemon/daemon.py
  lbry/wallet/network.py
Labels: area: files, type: improvement

#2974 added signed supports
  lbry/extras/daemon/daemon.py
  lbry/extras/daemon/json_response_encoder.py
  lbry/schema/claim.py
  lbry/schema/support.py
  lbry/schema/types/v2/support_pb2.py
  lbry/wallet/script.py
  lbry/wallet/transaction.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: wallet, type: new feature
