Repository lbryio/lbry-sdk, pull requests merged in 2020-04, with the labels that each got.

#2901 replaced `--unspent` with `--is_not_spent` on several commands and added `--is_spent` to many claim/txo `*_list` commands, `support_list` got three new flags `--sent --received --staked`
  lbry/extras/daemon/daemon.py
  lbry/wallet/database.py
  lbry/wallet/ledger.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature

#2902 bump checkpoints
  lbry/wallet/checkpoints.py
Labels: area: wallet, type: fixup, type: task

#2905 fix header checkpoints on testnet
  lbry/wallet/ledger.py
Labels: area: wallet, type: fixup

#2897 handle claim reorgs in the wallet server
  lbry/wallet/orchstr8/node.py
  lbry/wallet/server/block_processor.py
  lbry/wallet/server/db/writer.py
  lbry/wallet/server/prometheus.py
  tests/integration/blockchain/test_blockchain_reorganization.py
Labels: area: wallet server, type: new feature

#2909 do not estimate timestamp for unconfirmed txs
  lbry/wallet/header.py
  tests/unit/wallet/test_headers.py
Labels: area: wallet, type: bug

#2910 Comment_hide update
  .github/workflows/main.yml
  lbry/extras/daemon/daemon.py
  tests/integration/other/test_comment_commands.py
Labels: area: commenting, type: improvement

#2912 add `reflector_progress` to `file_list` results
  lbry/extras/daemon/json_response_encoder.py
  lbry/stream/managed_stream.py
  tests/unit/stream/test_reflector.py
Labels: area: files, type: new feature

#2911 support `claim_id`, `channel_claim_id`, and `outpoint` args given as lists of values to match in `file_list`
  lbry/extras/daemon/daemon.py
  lbry/stream/stream_manager.py
  tests/integration/datanetwork/test_file_commands.py
Labels: area: files, type: new feature

#2919 fix issue with `--exclude_internal_transfers` where it was filtering out sent payments
  lbry/wallet/database.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: bug

#2917 improve how claim search query handles reposts
  lbry/wallet/server/db/reader.py
Labels: area: wallet server, type: improvement

#2920 add `uploading_to_reflector` to `file_list` results
  lbry/extras/daemon/json_response_encoder.py
  lbry/stream/managed_stream.py
  lbry/wallet/__init__.py
Labels: area: files, type: new feature

#2924 fix for `claim_list` incorrectly handling `--is_spent` flag
  lbry/extras/daemon/daemon.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: cli, type: bug

#2925 fix: reposts being returned for single tags
  lbry/wallet/server/db/reader.py
Labels: area: claims, type: bug

#2926 make file i/o in stream and blob creation and reads non-blocking
  lbry/blob/blob_file.py
  lbry/blob_exchange/client.py
  lbry/stream/descriptor.py
  lbry/stream/managed_stream.py
  tests/unit/blob/test_blob_manager.py
  tests/unit/blob_exchange/test_transfer_blob.py
Labels: area: blobs/files, type: improvement

#2914 use home directory if xdg directory not found (Linux)
  Makefile
  lbry/conf.py
Labels: area: config, type: bug

#2922 estimate block timestamps on client only when necessary (header hasn't been downloaded yet)
  lbry/wallet/header.py
  tests/unit/wallet/test_database.py
  tests/unit/wallet/test_headers.py
  tests/unit/wallet/test_ledger.py
Labels: area: wallet, type: improvement

#2934 don't close the wallet server connection upon a cancelled request
  lbry/wallet/network.py
Labels: area: wallet, type: bug
