Repository lbryio/lbry-sdk, pull requests merged in 2020-02, with the labels that each got.

#2756 resolve errors make distinction between truely not found claims and claims which were censored by wallet server
  lbry/error/README.md
  lbry/error/__init__.py
  lbry/error/generate.py
  lbry/schema/result.py
  lbry/wallet/ledger.py
  lbry/wallet/server/db/reader.py
  tests/integration/blockchain/test_claim_commands.py
  tests/integration/blockchain/test_internal_transaction_api.py
  tests/integration/blockchain/test_resolve_command.py
  tests/integration/other/test_chris45.py
  tests/unit/wallet/server/test_sqldb.py
Labels: area: claims, type: improvement

#2757 added `--resolve` to local `claim_list`/`stream_list`/`channel_list` commands which returns more metadata for local claims
  docs/api.json
  lbry/extras/daemon/daemon.py
  lbry/testcase.py
  lbry/wallet/database.py
  lbry/wallet/ledger.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature

#2758 update copyright year in license
  LICENSE
Labels: area: packaging, type: improvement

#2761 catch TimeoutError when attempting to send notifications
  lbry/wallet/server/session.py
Labels: area: wallet server, type: fixup

#2760 added database index for several `channel_hash` based queries
  lbry/wallet/server/db/writer.py
Labels: area: wallet server, type: improvement

#2762 cancel reflector uploads upon file delete
  lbry/blob/blob_file.py
  lbry/blob_exchange/server.py
  lbry/extras/daemon/daemon.py
  lbry/stream/stream_manager.py
  tests/unit/blob_exchange/test_transfer_blob.py
Labels: area: files, type: bug

#2764 Add version tracking to prometheus metrics
  lbry/wallet/rpc/session.py
  lbry/wallet/server/block_processor.py
  lbry/wallet/server/prometheus.py
  lbry/wallet/server/session.py
Labels: area: wallet server, type: improvement

#2770 Add `save_resolved_claims` config setting for better performance when not using file_x commands
  lbry/conf.py
  lbry/extras/daemon/daemon.py
Labels: area: config, type: new feature

#2776 `resolve` results which are censored now include full details of channel which did the censoring
  lbry/error/README.md
  lbry/error/__init__.py
  lbry/error/base.py
  lbry/error/generate.py
  lbry/schema/result.py
  lbry/schema/types/v2/result_pb2.py
  lbry/wallet/server/db/reader.py
  lbry/wallet/server/db/writer.py
  tests/integration/blockchain/test_claim_commands.py
  tests/integration/blockchain/test_resolve_command.py
  tests/integration/other/test_chris45.py
Labels: area: api, type: improvement

#2777 `claim_list` argument `--claim_type` can now be repeated to pass a list of claim_types
  lbry/extras/daemon/daemon.py
  lbry/wallet/database.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: improvement

#2779 build community PRs using GitHub Actions
  .github/workflows/main.yml
  .gitlab-ci.yml
  tests/integration/other/test_transcoding.py
Labels: area: tests, type: improvement

#2773 fix video analysis error
  lbry/file_analysis.py
  lbry/wallet/orchstr8/node.py
Labels: area: blobs/files, type: improvement

#2768 update cffi to v1.13.2
  setup.py
Labels: area: packaging, type: improvement

#2765 fixed some issues with AR trending
  lbry/wallet/server/db/trending/ar.py
Labels: area: discovery, type: improvement

#2771 update url regex to include missing cases
  lbry/schema/url.py
  tests/integration/other/test_comment_commands.py
  tests/unit/schema/test_url.py
Labels: area: claims, type: bug

#2789 update default wallet servers
  scripts/test_claim_search.py
  tests/integration/other/test_other_commands.py
Labels: area: config, type: improvement

#2790 SQL generation fix to handle IN operation for one value lists
  lbry/wallet/database.py
  lbry/wallet/server/db/common.py
  lbry/wallet/server/db/reader.py
  lbry/wallet/server/db/writer.py
  setup.cfg
  tests/integration/blockchain/test_claim_commands.py
  tests/unit/wallet/test_database.py
Labels: area: wallet server, type: bug

#2796 linux build of LBRY SDK for Ubuntu 16.04 Xenial
  .gitlab-ci.yml
Labels: area: packaging, type: improvement

#2798 Add sqlite index for reposted claims
  lbry/extras/daemon/daemon.py
  lbry/wallet/server/db/writer.py
Labels: area: wallet server, type: improvement

#2800 Fix race condition setting/clearing the claim_search and resolve cache
  lbry/wallet/server/block_processor.py
Labels: area: wallet server, type: bug

#2803 fix claim apis failing with --resolve if no claims are present
  lbry/wallet/ledger.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: wallet, type: bug

#2806 change default privacy setting
  lbry/conf.py
  tests/unit/stream/test_stream_manager.py
  tests/unit/test_cli.py
Labels: area: config, type: improvement

#2810 removed default `order_by` for `claim_search`
  lbry/wallet/server/db/reader.py
Labels: area: wallet server, type: improvement

#2707 wallet servers requiring a daily fee will automatically get paid by client
  lbry/conf.py
  lbry/extras/daemon/components.py
  lbry/testcase.py
  lbry/wallet/orchstr8/node.py
  lbry/wallet/server/env.py
  lbry/wallet/server/session.py
  lbry/wallet/usage_payment.py
  tests/integration/blockchain/test_network.py
  tests/integration/blockchain/test_wallet_server_sessions.py
  tests/integration/other/test_cli.py
  tests/unit/components/test_component_manager.py
Labels: area: wallet server, type: new feature

#2815 apply share_usage_data as its set, without restarting
  lbry/extras/cli.py
  lbry/extras/daemon/analytics.py
  lbry/extras/daemon/loggly_handler.py
  tests/integration/other/test_other_commands.py
  tests/unit/test_cli.py
Labels: area: api, type: improvement

#2819 add MAX_RECEIVE setting to wallet server
  lbry/wallet/server/env.py
  lbry/wallet/server/session.py
Labels: area: wallet server, type: improvement

#2820 disconnect from client sending message larger than MAX_RECEIVE
  lbry/wallet/network.py
  lbry/wallet/rpc/session.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: wallet server, type: bug

#2821 add `ffmpeg_find` api to check ffmpeg installation status, don't recheck for ffmpeg in `status`
  lbry/extras/daemon/daemon.py
  lbry/file_analysis.py
Labels: area: api, type: new feature

#2822 use stream controller and documented errors for wallet server payments
  lbry/error/README.md
  lbry/error/__init__.py
  lbry/wallet/usage_payment.py
  tests/integration/blockchain/test_wallet_server_sessions.py
Labels: area: wallet, type: refactor

#2772 Add `is_fully_reflected` to `file_list` response
  lbry/extras/daemon/json_response_encoder.py
  lbry/extras/daemon/storage.py
  lbry/stream/managed_stream.py
  lbry/stream/stream_manager.py
Labels: area: files, type: new feature

#2824 max wallet server payment fee defaults to 0 and component doesnt start when its not a positive value
  lbry/conf.py
  lbry/wallet/usage_payment.py
  tests/integration/blockchain/test_wallet_server_sessions.py
Labels: area: config, type: improvement

#2825 use the stream controller tx instead of local history
  tests/integration/blockchain/test_wallet_server_sessions.py
Labels: area: tests, type: fixup

#2826 `claim_search --not_channel_ids` excludes the channel itself and not just claims in the channel
  lbry/testcase.py
  lbry/wallet/server/db/reader.py
  tests/integration/blockchain/test_claim_commands.py
  tests/integration/blockchain/test_purchase_command.py
  tests/integration/blockchain/test_resolve_command.py
  tests/integration/other/test_chris45.py
Labels: area: wallet server, type: bug

#2827 reposts inherit the tags of the original claim, filtered/blocked claims cause their reposts to also be filtered/blocked
  lbry/schema/result.py
  lbry/testcase.py
  lbry/wallet/server/db/reader.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: discovery, type: improvement

#2828 update lbrycrd in tests to v0.17.4.3
  lbry/wallet/__init__.py
Labels: area: tests, type: improvement

#2816 removes ability to comment anonymously
  lbry/extras/daemon/daemon.py
  scripts/generate_json_api.py
  tests/integration/other/test_comment_commands.py
Labels: area: commenting, type: improvement

#2831 update `claim_type_*` db indexes to be more performant
  lbry/wallet/server/db/writer.py
Labels: area: wallet server, type: improvement

#2834 when using `--resolve` with local claim `*_list` commands, update resolved result with local metadata (such as `is_mine`)
  lbry/wallet/ledger.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: improvement
