Repository lbryio/lbry-sdk, pull requests merged in 2020-03, with the labels that each got.

#2835 Improve wallet server performance with separate thread pools for leveldb, the block processor, and mempool
  lbry/wallet/server/block_processor.py
  lbry/wallet/server/leveldb.py
  lbry/wallet/server/mempool.py
Labels: area: wallet server, type: improvement

#2836 Add LRU caches for blocks and block hashes in the wallet server
  lbry/wallet/server/daemon.py
  lbry/wallet/server/mempool.py
Labels: area: wallet server, type: improvement

#2839 use `os.path.join()` instead of string addition when searching for file analysis binaries
  lbry/file_analysis.py
Labels: area: files, type: bug

#2840 `status` command returns features available of currently connected wallet server, including trending algorithm
  lbry/extras/daemon/components.py
  lbry/wallet/network.py
  lbry/wallet/server/db/writer.py
  lbry/wallet/server/env.py
  lbry/wallet/server/session.py
  tests/integration/blockchain/test_network.py
Labels: area: wallet server, type: new feature

#2793 don't validate and repair files that aren't videos; add maximum video bit rate setting
  lbry/conf.py
  lbry/extras/daemon/daemon.py
  lbry/file_analysis.py
  lbry/schema/mime_types.py
  scripts/check_video.py
  tests/integration/other/test_transcoding.py
Labels: area: blobs/files, type: improvement

#2845 fix DHT setup and disable ffmpeg on windows temporarily
  lbry/extras/cli.py
  lbry/file_analysis.py
Labels: area: asyncio, type: bug

#2842 revert LD_LIBRARY_PATH before calling ffmpeg
  lbry/file_analysis.py
  lbry/utils.py
  tests/integration/other/test_transcoding.py
Labels: area: packaging, type: bug

#2846 added `is_spent` attribute to transaction outputs
  lbry/extras/daemon/json_response_encoder.py
  lbry/testcase.py
  lbry/wallet/database.py
  lbry/wallet/ledger.py
  lbry/wallet/transaction.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature

#2848 added new `txo_list` command with filtering for `--claim_id`, claim `--name` and `--is_received`/`--is_not_received`, also commands `claim_list`/`stream_list`/`channel_list`/`support_list` are based on `txo_list` and thus support most of the new filters
  lbry/extras/daemon/daemon.py
  lbry/extras/daemon/json_response_encoder.py
  lbry/testcase.py
  lbry/wallet/account.py
  lbry/wallet/constants.py
  lbry/wallet/database.py
  lbry/wallet/ledger.py
  lbry/wallet/transaction.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature

#2857 Trending algorithm with time delay and variable decay rate
  lbry/wallet/server/db/trending/__init__.py
  lbry/wallet/server/db/trending/variable_decay.py
Labels: area: discovery, type: new feature

#2854 Adds tracemalloc api for memory troubleshooting
  lbry/extras/daemon/daemon.py
  tests/integration/other/test_other_commands.py
Labels: area: api, type: new feature

#2866 fixed issue with shell parsing on Windows
  lbry/file_analysis.py
Labels: area: blobs/files, type: bug

#2865 upgrade lbrycrd to v0.17.4.4
  lbry/wallet/__init__.py
Labels: area: tests, type: improvement

#2823 Use multiple processes for querying the db for api calls
  lbry/extras/daemon/daemon.py
  lbry/wallet/account.py
  lbry/wallet/database.py
  lbry/wallet/ledger.py
  tests/unit/wallet/test_database.py
Labels: area: database, type: new feature

#2851 Add `blockchain.transaction.info` and `blockchain.transaction.get_batch` to the wallet server for more efficient transaction fetching
  lbry/wallet/server/daemon.py
  lbry/wallet/server/session.py
Labels: area: wallet server, type: new feature

#2862 `txo_list` adds many new ownership filters such as `--is_my_input`, `--is_my_output`, etc and some metadata filters such as `--channel_id`, `--reposted_claim_id`, etc and a new command `txo_sum` which takes the same arguments as `txo_list` and produces sum of outputs
  lbry/extras/daemon/daemon.py
  lbry/extras/daemon/json_response_encoder.py
  lbry/testcase.py
  lbry/wallet/account.py
  lbry/wallet/database.py
  lbry/wallet/ledger.py
  lbry/wallet/transaction.py
  tests/integration/blockchain/test_claim_commands.py
  tests/integration/blockchain/test_transactions.py
  tests/integration/blockchain/test_wallet_commands.py
  tests/unit/test_cli.py
  tests/unit/wallet/test_database.py
  tests/unit/wallet/test_transaction.py
Labels: area: api, type: new feature

#2870 added new flags to `resolve` (and a few to `claim_search`) commands: `--include_purchase_receipt`, `--include_is_my_output`, `--include_sent_supports`, `--include_sent_tips` and `--include_received_tips`
  lbry/extras/daemon/daemon.py
  lbry/extras/daemon/json_response_encoder.py
  lbry/stream/stream_manager.py
  lbry/testcase.py
  lbry/wallet/database.py
  lbry/wallet/ledger.py
  lbry/wallet/transaction.py
  tests/integration/blockchain/test_purchase_command.py
  tests/integration/blockchain/test_resolve_command.py
  tests/unit/stream/test_stream_manager.py
Labels: area: api, type: new feature

#2871 fix to prevent transaction cache from leaking some information about outputs between unrelated wallets
  lbry/extras/daemon/daemon.py
  lbry/wallet/ledger.py
  tests/integration/blockchain/test_purchase_command.py
  tests/integration/blockchain/test_resolve_command.py
Labels: area: wallet, type: bug

#2872 added `--include_received_tips` to `claim_list` and `txo_list` commands
  lbry/extras/daemon/daemon.py
  lbry/wallet/database.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature

#2863 fetch headers on demand
  lbry/extras/daemon/components.py
  lbry/extras/daemon/json_response_encoder.py
  lbry/stream/stream_manager.py
  lbry/testcase.py
  lbry/wallet/checkpoints.py
  lbry/wallet/header.py
  lbry/wallet/ledger.py
  lbry/wallet/manager.py
  lbry/wallet/orchstr8/node.py
  scripts/checkpoints.py
  tests/integration/blockchain/test_blockchain_reorganization.py
  tests/integration/blockchain/test_network.py
  tests/integration/blockchain/test_resolve_command.py
  tests/integration/blockchain/test_sync.py
  tests/integration/datanetwork/test_file_commands.py
  tests/unit/lbrynet_daemon/test_Daemon.py
  tests/unit/stream/test_stream_manager.py
  tests/unit/wallet/test_headers.py
  tests/unit/wallet/test_ledger.py
Labels: area: wallet, type: improvement

#2877 wait for tx sync to finish but not header sync
  lbry/testcase.py
  lbry/wallet/ledger.py
  lbry/wallet/orchstr8/node.py
  tests/integration/blockchain/test_resolve_command.py
  tests/integration/blockchain/test_sync.py
Labels: area: wallet, type: fixup

#2884 added `txo_plot` command to allow plotting txo sums over time
  lbry/extras/daemon/daemon.py
  lbry/testcase.py
  lbry/wallet/database.py
  lbry/wallet/header.py
  lbry/wallet/ledger.py
  lbry/wallet/transaction.py
  lbry/wallet/util.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature

#2852 More efficient syncing of wallet transactions
  lbry/wallet/account.py
  lbry/wallet/ledger.py
  lbry/wallet/manager.py
  lbry/wallet/network.py
  tests/unit/wallet/test_ledger.py
Labels: area: wallet, type: improvement

#2881 add `wallet_syncing` to `status`, which is set to true when processing transaction updates
  lbry/extras/daemon/daemon.py
  lbry/wallet/ledger.py
  lbry/wallet/tasks.py
  tests/integration/blockchain/test_wallet_commands.py
Labels: area: api, area: wallet, type: new feature

#2888 add m4a content type
  lbry/schema/mime_types.py
Labels: area: blobs/files, type: improvement

#2893 fix estimated timestamp to return integer instead of float
  lbry/wallet/header.py
  tests/integration/blockchain/test_wallet_server_sessions.py
Labels: area: api, type: bug

#2896 fix for startup issues when connecting to wallet servers
  lbry/wallet/ledger.py
  tests/integration/blockchain/test_network.py
  tests/integration/blockchain/test_wallet_server_sessions.py
Labels: area: network, type: bug

#2887 added `txo_spend` command to support liquidating large number of txos (eg. tips) by batching them across several transactions
  lbry/extras/daemon/daemon.py
  lbry/testcase.py
  lbry/wallet/ledger.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature

#2885 repair headers tip on open and let new headers come in during background fetching
  lbry/wallet/header.py
  lbry/wallet/ledger.py
  tests/unit/wallet/test_headers.py
Labels: area: wallet, type: improvement

#2890 improve speed of `status`
  lbry/extras/daemon/daemon.py
  lbry/file_analysis.py
  tests/integration/other/test_transcoding.py
Labels: area: api, type: improvement

#2898 `ffmpeg` file analysis returns duration as integer now
  lbry/file_analysis.py
  tests/integration/other/test_transcoding.py
Labels: area: blobs/files, type: bug
