Repository lbryio/lbry-sdk, pull requests merged in 2021-08, with the labels that each got.

#3383 DHT: log invalid port as a warning instead of an exception
  lbry/dht/peer.py
  lbry/dht/protocol/protocol.py
Labels: type: improvement, area: DHT

#3395 make libtorrent optional and skip test which depends on it
  tests/integration/datanetwork/test_file_commands.py
Labels: area: tests, type: testing

#3378 ability to limit disk spaced used for blobs via `blob_storage_limit` setting (oldest blobs are deleted when disk space limit is reached)
  .github/workflows/main.yml
  lbry/blob/disk_space_manager.py
  lbry/conf.py
  lbry/extras/daemon/components.py
  lbry/extras/daemon/daemon.py
  lbry/testcase.py
  tests/integration/datanetwork/test_file_commands.py
  tests/unit/blob/test_disk_space_manager.py
  tests/unit/components/test_component_manager.py
  tests/unit/test_conf.py
Labels: type: new feature, area: blobs/files

#3398 clean blobs after waiting interval instead of immediately on startup
  lbry/blob/disk_space_manager.py
Labels: type: improvement, area: blobs/files

#3399 Less verbose error logs, only log tracebacks for errors not defined in `lbry.error`
  lbry/error/README.md
  lbry/error/__init__.py
  lbry/extras/daemon/daemon.py
  lbry/wallet/manager.py
Labels: type: improvement, area: api

#3402 changed default setting `save_files` to be false
  lbry/conf.py
  lbry/testcase.py
  tests/unit/blob_exchange/test_transfer_blob.py
  tests/unit/stream/test_stream_manager.py
Labels: type: improvement, area: config

#3405 upgrade pylint and fix lint errors
  Makefile
  lbry/conf.py
  lbry/dht/protocol/protocol.py
  lbry/dht/protocol/routing_table.py
  lbry/dht/serialization/datagram.py
  lbry/error/generate.py
  lbry/extras/cli.py
  lbry/extras/daemon/daemon.py
  lbry/extras/daemon/json_response_encoder.py
  lbry/extras/daemon/storage.py
  lbry/file_analysis.py
  lbry/stream/managed_stream.py
  lbry/utils.py
  lbry/wallet/account.py
  lbry/wallet/bip32.py
  lbry/wallet/database.py
  setup.cfg
  setup.py
Labels: type: improvement, area: other
