Repository lbryio/lbry-sdk, pull requests merged in 2021-01, with the labels that each got.

#3134 log checkpoint finishing so we can gather information on leftover files bug
  lbry/wallet/database.py
Labels: area: other, type: improvement

#3135 add prometheus metrics for asyncio loop
  lbry/prometheus.py
  tests/integration/other/test_exchange_rate_manager.py
Labels: area: wallet server, type: improvement

#3129 add `channel_sign` api for signing data with a channel identity
  lbry/extras/daemon/comment_client.py
  lbry/extras/daemon/daemon.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: wallet, type: new feature

#3136 fix reflector loop crashing upon an unexpected error
  lbry/stream/managed_stream.py
  lbry/stream/stream_manager.py
  tests/unit/stream/test_reflector.py
Labels: area: reflector, type: bug

#3160 added support for `--not_channel_id` to `txo_list` commands
  lbry/extras/daemon/daemon.py
  lbry/wallet/database.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature

#3148 UDP based spv server status, improved server selection
  lbry/blob/blob_manager.py
  lbry/dht/peer.py
  lbry/extras/daemon/analytics.py
  lbry/extras/daemon/components.py
  lbry/testcase.py
  lbry/utils.py
  lbry/wallet/ledger.py
  lbry/wallet/network.py
  lbry/wallet/server/block_processor.py
  lbry/wallet/server/daemon.py
  lbry/wallet/server/leveldb.py
  lbry/wallet/server/server.py
  lbry/wallet/server/session.py
  lbry/wallet/server/udp.py
  tests/integration/blockchain/test_network.py
  tests/integration/blockchain/test_wallet_commands.py
  tests/integration/blockchain/test_wallet_server_sessions.py
  tests/integration/datanetwork/test_file_commands.py
  tests/integration/other/test_cli.py
Labels: area: wallet server, type: new feature

#3161 handle connections from ledger clients in spv server
  lbry/wallet/server/mempool.py
  lbry/wallet/server/session.py
Labels: area: wallet server, type: new feature

#3162 Fix mimetypes for HLS streams, add mimetypes for segment files
  lbry/schema/mime_types.py
Labels: area: blobs/files, type: improvement

#3172 `txo_list --resolve` now works for signed supports by resolving the signing channel
  lbry/wallet/ledger.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: new feature
