Repository lbryio/lbry-sdk, pull requests merged in 2021-05, with the labels that each got.

#3293 fix invalid claim fees breaking the block processor
  lbry/wallet/server/db/writer.py
Labels: area: hub, type: bug

#3262 Fix bug for `has_source=True` hiding channel reposts
  lbry/wallet/server/db/elasticsearch/search.py
  lbry/wallet/server/db/elasticsearch/sync.py
  lbry/wallet/server/db/writer.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: hub, type: bug

#3294 add versioning to ES search index and automate resync on version bumps
  lbry/wallet/server/db/elasticsearch/search.py
  lbry/wallet/server/db/elasticsearch/sync.py
Labels: area: hub, type: improvement

#3305 fix hub Elasticsearch sync/migrations tool for when the db exists already
  lbry/wallet/server/db/elasticsearch/search.py
  lbry/wallet/server/db/elasticsearch/sync.py
  tests/integration/blockchain/test_wallet_server_sessions.py
Labels: area: hub, type: bug

#3307 remove unused multiprocessing.Manager, decreasing hub memory usage significantly
  lbry/wallet/server/db/writer.py
Labels: area: hub, type: improvement

#3306 fix bug in collection_update --replace
  lbry/extras/daemon/daemon.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: api, type: bug

#3308 Don't set stream as reflected until reflector says it doesn't need any blob
  lbry/stream/managed_stream.py
  lbry/stream/reflector/client.py
  lbry/stream/reflector/server.py
  lbry/stream/stream_manager.py
  tests/unit/stream/test_reflector.py
Labels: area: blobs/files, type: bug
