Repository lbryio/lbry-sdk, pull requests merged in 2021-02, with the labels that each got.

#3171 allows cli to accept channel_id for collections
  lbry/extras/daemon/daemon.py
Labels: area: cli, type: improvement

#3183 updated exchange rate manager to use v3 bittrex API (v1.1 is deprecated)
  lbry/extras/daemon/exchange_rate_manager.py
  tests/integration/other/test_exchange_rate_manager.py
  tests/unit/lbrynet_daemon/test_exchange_rate_manager.py
Labels: area: resilience, type: improvement

#3192 ensures content purchase fails appropriately when exchange rate is not available
  tests/integration/blockchain/test_purchase_command.py
Labels: area: wallet, type: improvement

#3195 use median exchange rate when several exchange rates are available
  lbry/extras/daemon/exchange_rate_manager.py
  tests/unit/lbrynet_daemon/test_exchange_rate_manager.py
Labels: area: wallet, type: improvement

#3198 added support to `claim_search` for filtering collections via `--claim_type=collection`
  lbry/extras/daemon/daemon.py
  lbry/wallet/server/db/common.py
  lbry/wallet/server/db/writer.py
  tests/integration/blockchain/test_claim_commands.py
Labels: area: claims, type: new feature
