Repository lbryio/lbry-sdk, pull requests merged in 2022-10, with the labels that each got.

#3684 wallet import/export supports plain JSON (without supplying a password)
  lbry/extras/daemon/daemon.py
  lbry/wallet/wallet.py
  tests/integration/blockchain/test_wallet_commands.py
Labels: area: wallet, type: new feature

#3689 update checkpoints for faster first run header download
  lbry/wallet/checkpoints.py
Labels: type: improvement, area: wallet

#3685 added `claim_list` filtering by `--reposted_claim_id` and fix for `claim_id` of reposted claim in JSON output
  lbry/extras/daemon/daemon.py
  lbry/schema/claim.py
  tests/integration/claims/test_claim_commands.py
Labels: type: new feature, area: api

#3695 Fix claim fields fallback raising errors before download is saved on database
  lbry/file/file_manager.py
  tests/integration/datanetwork/test_file_commands.py
Labels: type: bug, area: files

#3700 `channel_sign` command gained `--salt` parameter to customize salt to use for signing
  lbry/extras/daemon/daemon.py
  tests/integration/claims/test_claim_commands.py
Labels: type: new feature, area: api
